http:
  hostName:        "0.0.0.0"
  port:            "8081"


american:
  host:            "proxy-avier-american-flights-sapi.us-e2.cloudhub.io"
  port:            "80"
  basePath:        "/"
  protocol:        "HTTP"