# Properties for HTTP Listener configuration
http:
  hostName:        "0.0.0.0"
  port:            "8081"

# Properties for Accounts API configuration
accounts:
  hostName:        "proxy-avier-accounts-sapi.us-e2.cloudhub.io"
  port:            "80"
  basePath:        "/"
  protocol:        "HTTP"

# Properties for Transaction Web service configuration
transactions:
  wsdl:             "http://mu.mule-training.com/transactions?wsdl"
  service:          "TransactionsServiceService"
  port:             "TransactionsServiceImplPort"
  address:          "http://mu.mule-training.com/transactions"