#%RAML 1.0 NamedExample
NewAccountsExample:
  -
    name: EMCA
    type: business
    address: "1 Main St,Los Angeles,CA,92000,USA"
    airMiles: 500
  - 
    name: John Doe
    type: personal
    address: "1 Main St,Los Angeles,CA,92000,USA"
    airMiles: 2600